import { library } from "@fortawesome/fontawesome-svg-core";
import {
  faTwitter,
  faDiscord,
  faFacebookSquare,
  faInstagram,
  faGithub,
  faLinkedin,
  faAngellist,
} from "@fortawesome/free-brands-svg-icons";
import {
  faCommentAlt,
  faEllipsisV,
  faEllipsisH,
  faAt,
  faQuestionCircle,
  faPlus,
  faPlusCircle,
  faUserFriends,
  faUserPlus,
  faMicrophone,
  faHeadphonesAlt,
  faCog,
  faCompass,
  faDownload,
  faCrown,
  faPen,
  faDotCircle,
  faAngleDown,
  faHashtag,
  faVolumeUp,
  faBell,
  faMoon,
  faLock,
  faArrowAltCircleLeft,
  faSearch,
  faThumbtack,
  faArrowLeft,
} from "@fortawesome/free-solid-svg-icons";
import { faTimesCircle } from "@fortawesome/free-regular-svg-icons";

library.add(
  faArrowLeft,
  faGithub,
  faLinkedin,
  faAngellist,
  faTwitter,
  faDiscord,
  faFacebookSquare,
  faInstagram,
  faCommentAlt,
  faEllipsisV,
  faEllipsisH,
  faAt,
  faQuestionCircle,
  faPlus,
  faPlusCircle,
  faUserFriends,
  faUserPlus,
  faMicrophone,
  faHeadphonesAlt,
  faCog,
  faCompass,
  faDownload,
  faCrown,
  faPen,
  faDotCircle,
  faAngleDown,
  faHashtag,
  faVolumeUp,
  faBell,
  faMoon,
  faLock,
  faArrowAltCircleLeft,
  faSearch,
  faThumbtack,
  faTimesCircle
);
